### ISSUE TITLE
Cannot set result_ttl=0 in RQ.job

### ISSUE THREAD

**Issue by serathius** [jezdez/Flask-RQ2#28]
https://github.com/jezdez/Flask-RQ2/blob/master/src/flask_rq2/app.py#L262
should be
`result_ttl=DEFAULT_RESULT_TTL if result_ttl is None else result_ttl`
so if `result_ttl = 0` passed value is not overwritten with `DEFAULT_RESULT_TTL`

**Comment by jezdez** [comment]
Good catch, and d'oh!
