### ISSUE TITLE
Timeout in cron

### ISSUE THREAD

**Issue by ZUNbado** [jezdez/Flask-RQ2#31]
Hi there,

The module rq-scheduler permit to set a timeout in cronjobs, but this flask plugin not allows

You can view cron function definition in https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/scheduler.py#L188
`    def cron(self, cron_string, func, args=None, kwargs=None, repeat=None,
             queue_name=None, id=None, timeout=None, description=None):`

But in flask plugin the call is this
`def cron(self, pattern, name, *args, **kwargs):`

I need to set timeout to cronjobs according rq_scheduler module.

Kind regards

**Comment by jkehler** [comment]
I've created a PR that fixes this issue. #34

**Comment by jezdez** [comment]
Thank you @jkehler, this got merged.
