### ISSUE TITLE
Please, update docs; form_url exists no more

### ISSUE THREAD

**Issue by italomaia** [jezdez/Flask-RQ2#46]
Docs cite a method called form_url, which is no longer available at redis-py. https://flask-rq2.readthedocs.io/en/latest/#rq-redis-url

**Comment by jezdez** [comment]
@italomaia This is just a typo, the correct name of the parameter is ``from_url``, which [is still there](https://github.com/andymccurdy/redis-py/blob/5109cb4f6b610e8d5949716a16435afbbf35075a/redis/client.py#L461-L488). I've fixed the docs in https://github.com/jezdez/Flask-RQ2/commit/515898ca7f2286a2f1d22b274e02324f05c9eac5.
